@startuml

@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam linetype ortho
scale 2

class NetObjBase {
    +__init__()
    +__str__()
}

class Device {
    +__init__()
    +__str__()
}

class Interface {
    +__init__()
    +__str__()
}

class Connection {
    +__init__()
    +__str__()
}

class Network {
    +__init__()
    +__str__()
}

class DotGenerator {
    -devices
    -interfaces
    -connections
    -networks

    +__init__()
    +addDevice()
    +addInterfaces()
    +addConnection()
    +addNetwork()
    +fromDict()
    +__str__()
}

NetObjBase <-- Device
NetObjBase <-- Interface
NetObjBase <-- Connection
NetObjBase <-- Network

Device -- DotGenerator
Interface -- DotGenerator
Connection -- DotGenerator
Network -- DotGenerator

@enduml